# Generated by Django 4.1 on 2022-09-06 01:50

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50, unique=True)),
                ('channel_creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_birth_date', models.DateTimeField(default=None, verbose_name='The date the user was born. Optional')),
                ('user_register_date', models.DateTimeField(default=videos.models.User.get_date, verbose_name='The date the user registered')),
                ('user_last_joined_date', models.DateTimeField(default=models.DateTimeField(default=videos.models.User.get_date, verbose_name='The date the user registered'), verbose_name='The last time the user was active')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='')),
                ('video_name', models.CharField(max_length=200)),
                ('video_description', models.TextField()),
                ('channel_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.channel')),
                ('user_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000)),
                ('comment_post_date', models.DateTimeField()),
                ('comment_is_edited', models.BooleanField()),
                ('comment_likes', models.IntegerField()),
                ('comment_dislikes', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.user')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.comment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.user'),
        ),
    ]
