# Generated by Django 4.1 on 2022-09-06 01:56

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_last_joined_date',
            field=models.DateTimeField(default=videos.models.User.get_date, verbose_name='The last time the user was active'),
        ),
    ]
