# Generated by Django 4.1 on 2022-09-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_user_user_last_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birth_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='The date the user was born. Optional'),
        ),
    ]
