# Generated by Django 4.1 on 2022-09-16 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_post_date_alter_comment_comment_is_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 0, 1, 0, 493635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 0, 1, 0, 493134, tzinfo=datetime.timezone.utc)),
        ),
    ]
