# Generated by Django 4.1 on 2022-09-16 00:03

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_comment_comment_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_post_date',
            field=models.DateTimeField(default=videos.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_date',
            field=models.DateTimeField(default=videos.models.get_current_date),
        ),
    ]
